### PR TITLE
Provide generic implementation of `bundle_samples` for `Vector{T}`

### PR DESCRIPTION
**Pull request by devmotion**
While updating AdvancedMH I noticed that we define a bunch of `bundle_samples` implementations there. I was wondering if we could generalize that in a way such that we don't have to repeat it in every package. In particular, it seems a bit strange to reimplement it in every package for `Vector{NamedTuple}` even though the only difference is how the samples are converted to a `NamedTuple`. But one could, e.g., also have a generic version for MCMCChains.Chains in MCMCChains with the basic structure + an interface for other packages to convert the samples, retrieve the names, the log-evidence + save the state, sampler, and model in a standardized way (and not different in every package).

This PR contains a very generic implementation for any desired vector-valued output.

### CODE REVIEW

**Comment by devmotion** [comment]
However, for AdvancedMH this would mean that the keyword argument `param_names` wouldn't be available anymore for `Vector{NamedTuple}` output. I'm wondering if that would be an issue? I guess users could still change the names afterwards (even for Chains) but requires an additional step?

**Comment by devmotion** [comment]
Ah wait, I guess one could just define `convert(::Type{NamedTuple{names}}, ::Transition)` in NamedTuples and then use `Vector{NamedTuple{names}}` as output type :+1:

**Comment by yebai** [comment]
@devmotion I fixed a merge conflict. Not sure it is what you intended to do. Pls, take a look anyway.

**Comment by devmotion** [comment]
Thanks, looks good to me!

**Pull request merged**
