### PR TITLE
Reversion of commits v4.4.2..v4.5.0

### PR DESCRIPTION
**Pull request by torfjelde**
This supersedes #132, as in that PR I didn't do a proper `git revert` of all the commits.

@yebai @devmotion

### CODE REVIEW

**Comment by devmotion** [comment]
No, 4.4.x to 4.5.0 is a non-breaking change. This is different from < 1.0.0 where 0.x to 0.x+1 is breaking.

**Comment by torfjelde** [comment]
> BTW wouldn't it be better to just yank 4.5.0 from the registry instead of reverting and releasing?

Oh most definitely! How do we go about doing this?

**Comment by devmotion** [comment]
https://github.com/JuliaRegistries/General/pull/94031

**Comment by torfjelde** [comment]
Should we just merge #134 and make a release then? While we wait for 4.5.0 to be yanked?

**Comment by devmotion** [comment]
Let's maybe wait ~2 hours to avoid merge conflicts in the registry? I pinged maintainers of the registry in https://julialang.slack.com/archives/C6M4DQA5P/p1698230734349069.

**Comment by devmotion** [comment]
The release is yanked.

**Pull request closed without merging**
