### PR TITLE
Add Documenter

### PR DESCRIPTION
**Pull request by devmotion**

### CODE REVIEW

**Comment by devmotion** [comment]
Preview: https://turinglang.github.io/AbstractMCMC.jl/previews/PR70/

**Comment by devmotion** [comment]
Seems Pages is not enabled?

**Review by cpfiffer — APPROVED** [review]
I think since the site is new we can just push this out and debug the doc site after this is merged into master.

**Comment by devmotion** [comment]
@cpfiffer can you enable Github Pages for the repo? I can't access the settings but it seems it is disabled currently (gh-pages exists and is updated by Documenter but the page is not deployed by Github).

**Comment by cpfiffer** [comment]
Hm, I did enable it but I'm not sure why it's not serving.

**Comment by devmotion** [comment]
It works now :+1:

**Pull request merged**
