### PR TITLE
Fix method ambiguity issues

### PR DESCRIPTION
**Pull request by devmotion**
Alternative to #120 which keeps the current functionality.

@torfjelde Do you have a MWE of the ambiguity issues? Or can confirm that this PR would fix the issues you ran into?

### CODE REVIEW

**Comment by torfjelde** [comment]
I'll have to dig out those examples; it's been a while. But will try to get around to it sometime today.

**Comment by devmotion** [comment]
Were you able to find (and run?) the examples?

**Comment by torfjelde** [comment]
No, sorry haven't done it yet. The original examples in #120 are from MCMCTempering.jl which I haven't done in a while. This PR most certainly helps with the overall issue we've discussed, whether or not it actuallly solves the particular ambiguity I ran into.

**Comment by devmotion** [comment]
Should we merge then maybe merge the PR and revisit #120 (or some variant) if problems show up again?

**Comment by torfjelde** [comment]
I'm happy with that:) I have NeurIPS reviews over the next few weeks, but once that's done I'll revisit MCMCTempering, and so might be able to provide some cases in #120 then :+1: But for now, let's just merge this.

**Review by torfjelde — APPROVED** [review]
Thanks David:)

**Pull request merged**
